kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${_SERVICE_ACCOUNT}
  namespace: ${_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: ${_SERVICE_ACCOUNT}
    namespace: ${_NAMESPACE}
roleRef:
  kind: Role
  name: ${_SERVICE_ACCOUNT}
  apiGroup: rbac.authorization.k8s.io
