kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${_SERVICE_ACCOUNT}
  namespace: ${_NAMESPACE}
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["deployments", "services", "replicasets", "pods", "jobs", "cronjobs"]
    verbs: ["*"]
