apiVersion: v1
kind: Secret
metadata:
  name: ${_SERVICE_ACCOUNT}-secret
  namespace: ${_NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: ${_SERVICE_ACCOUNT}
type: kubernetes.io/service-account-token
